### ISSUE TITLE
Alternative

### ISSUE THREAD

**Issue by vincent-laizer** [Diggerati/secondary-schools-tanzania-2021#1]
Just a suggestion, why not use nectaapi
 ```python
    from nectaapi import schools
    data = schools.schools(2017, 'csee') 
```

check it out at [PyPI](https://pypi.org/project/nectaapi/)

**Comment by Diggerati** [comment]
I was just creating to help a friend to scrap schools. and I was unaware of
the nectaapi
Regards,
Innocent Masuki.

**Comment by Diggerati** [comment]
It is a really best choice to solve the thing for all years... thank you alot @vincent-laizer
